name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install tools
      run: sudo apt-get install gettext
    - name: delete old files
      run: rm prebuilt/gcc-zh.mo
    - name: po2mo
      run: msgfmt -o prebuilt/gcc-zh.mo gcc-zh.po
