name: autorelease

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get install gettext

    - name: Make .mo
      run: make

    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/*
        fail_on_unmatched_files: true
        tag_name: ${{ steps.bump.outputs.new_tag }}
